# Generated by Django 3.1 on 2021-12-28 05:40

import apps
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save_name', models.FileField(upload_to=apps.file_upload_path_for_db)),
                ('file_origin_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('file_ext', models.CharField(max_length=10)),
                ('is_img', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'file_box',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
